language: python
python:
  - "3.6"
  - "3.8"
  - "3.9"
cache: pip
before_install:
  - sudo apt-get -y install gcc gfortran
install:
  - pip install -r requirements.txt
script:
  - python imbot/telegramnote.py
  - python imbot/martas.py
  - python imbot/secondanalysis.py -D
  - python imbot/minuteanalysis.py -D
