language: python
python:
  - "2.7"
  - "3.7"
cache: pip
before_install:
  - sudo apt-get -y install gcc gfortran
install:
  - pip install -r requirements.txt
script:
  - python imbot/telegramnote.py
  - python imbot/martas.py
